version: "3.9"

networks:
  default:
    driver: bridge

services:
  proxy:
    # image: envoyproxy/envoy-dev:e4955aed5694f9935d674419dbb364e744f697b4
    image: envoyproxy/envoy:v1.21.0
    container_name: envoy-proxy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8080:8080"
    networks:
      - default
  db:
    image: redis:latest
    volumes:
      - ./redis/data:/data
    container_name: redis-db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - default
  server:
    build:
      context: ./server/
    container_name: node-server
    restart: always
    volumes:
      - ./server/:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - 9090:9090
    depends_on:
      - redis
      - envoy
    networks:
      - default
  client:
    build:
      context: ./client/
    container_name: react-client
    restart: always
    volumes:
      - ./client/:/app
      - ./client/node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - default
